### ISSUE TITLE
KLA notes

### ISSUE THREAD

**Issue by HughP** [HughP/tcf-james-bigramed#2]
@iandoug
I was working on this language for a minute and I threw the text into KLA to get some results. (you might find the method here interesting).

BUT: I wanted to know what was meant in KLA under the Miscellaneous tab where it says `How often the Shift, AltGr, and Shift+AltGr modifiers`  how does it know altgr states?

![modifier-key-use](https://user-images.githubusercontent.com/40230/41837121-7a01d41e-7811-11e8-9b08-542273bb9a8c.png)

**Comment by iandoug** [comment]
Well each letter/glyph is allocated to one of four slots on the key : normal, shifted, AltGr, and shift-AltGr.

So then if just checks if the letter is in the text, sees which slot it is in on the key, and adds shift or AltGr usage as required. 
BTW I need to fix the sample texts (and also layouts) on my Dan playground, they still have the wrong characters for tone marks. Will see if I can do that later today, got to run around a bit today.

Which version of KLA are you using? Your local copy?

**Comment by HughP** [comment]
I am using the local copy of KLA. But note this is Mephaa, not Dan.

**Comment by iandoug** [comment]
Okay. Think I mentioned it before but if the required character is not on the keyboard, KLA just ignores it, which affects the score vs keyboards that have that character.
Also it insists on including a hidden QWERTY layout in every comparison. Must try and remove that... and the automatic "personalised" layout generation.

**Comment by HughP** [comment]
I think my point is if it can detect AltGr then why can't it detect dead keys?

**Comment by HughP** [comment]
Well, I think the QWERTY analysis is the correct analysis if one takes the
steps in the README.md of tcf-*bigram repo.

**Comment by iandoug** [comment]
Deadkeys requires two key presses (at least). AltGr (and shift) is inferred from the slot on the key that the character is in. There are no explicit AltGr presses in the analyzed text, any more than there are explicit Shift presses ... it's inferred from the slot that the character is in.

To add Deadkeys we would need to add extra slots to every key ... normal, shifted and AltGr, and then update the logic to work backwards from a given character, eg Ë ... program needs to realise that that requires user to first press colon key, then Shift+e. 
Which I suppose in theory is doable. 
Then it also needs flag on one or more dead keys that indicates it is a dead key.
Then it also needs to know that every time for example there is a colon in the text, it needs to count two colon presses.

On top of that, if you want to do the French letters with deadkeys, then you need a whole bunch more as deadkeys (eg backtick, normal ASCII apostrophe, circumflex, comma, possibly tilde, as well as colon and/or ASCII double apostrophe) ... which means you're going to be double-tying a lot more things when you need those characters by themselves. As well as extra slots for example on E, to tell KLA what to do when the user presses ^E or :E or `e.

So yeah, I think it is doable (but I'm a programmer and just about anything is doable, some things are just easier than others.. :-) ) ....

But for Dan, I really don't think dead keys are the way to go. I've got everything on keys (admittedly some rare characters are on AltGr/Shift-AltGr), the only problem child I have is hook-v-diaeresis. Let me go ask on GeekHack for some pointers about that ...

**Comment by HughP** [comment]
What about if instead of looking at the character it looks at a string?
some strings will be a single multi-byte character, other strings will be
single byte characters, and even other strings will be multiple characters.
but the strings can be defined in JSON.

**Comment by iandoug** [comment]
Had a look at https://github.com/HughP/tcf-james-bigramed
That language seems more problematic that Dan, given the requirement to use combining diacritics to get the underscores (which I see the font here on Github does a bad job with).

I understand your thinking. At the moment KLA only takes single characters in each slot, which is why I'm faking hook-v-diaeresis by using upsilon-diaeresis instead.
I will have to have a look at the KLA code to see if I can persuade it do work with strings instead of single chars.
That raises the question of how it will work in the real world ... between the keyboard and the OS. 
Let me dig into that. Had to run out and just remembered about Geekhack now ... let me do that now before I forget.

**Comment by HughP** [comment]
In the real world,

xkb on linux can do strings (I think)
.keylayout on MacOS can do strings (I know)
.kmn and things like autohotkey can do strings because they are interpreted
KLC for windows can do strings up to something like 4 bytes.

**Comment by iandoug** [comment]
Excuse the newbie question/observation, but the kinda obvious (to me) solution is to put the macron above the letter rather than below it. Unicode supports that well. 
Getting rid of all those combining diacritics will make everyone's life easier going forward. Must be tedious typing them on a phone keyboard.

But I suppose it's already set in stone ... :-)

**Comment by HughP** [comment]
Been writing like that for about 30 years now... low tone below the word
and high tone above the word and no tone mark is mid tone....

**Comment by iandoug** [comment]
Apart from the logic of low tones below the word, I think 30 years ago it was way easier to type a line under a letter with a typewriter than above it.

Just read your diacritic analysis in the readme ... that's precisely why I took the approach I did, to eliminate having to type diacritics. Was not expecting to end up with three versions of /a/ on the home row though :-)
A while back I tried to get xkb to produce strings when single key hit, can't remember if I got it to work. Will try again tomorrow.

I "think" I know what is making my left pinky have such a high same-key figure, will try a few things. To do with speech starting with vowels on pinky. I swapped the obvious order because that was causing extra same-finger on right pinky (enter and shift).
